/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladoras.EquipoData;
import entidades.Equipo;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author nacho
 */
public class BuscarEquipoVista extends javax.swing.JInternalFrame {
    private EquipoData ed = new EquipoData();
    /**
     * Creates new form BuscarEquipoVista
     */
    public BuscarEquipoVista() {
        initComponents();
        btnDarDeBaja.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfIDEquipo = new javax.swing.JTextField();
        jtfIDProyecto = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfFechaCreacion = new javax.swing.JTextField();
        jtfEstado = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnDarDeBaja = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("-.-.-.-.-.-.-.-.-.-.-.-  BUSCAR EQUIPO -.-.-.-.-.-.-.-.-.-.-.-.-.-");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("ID Equipo:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("ID Proyecto:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Fecha Creacion:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Estado:");

        jtfIDEquipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtfIDProyecto.setEditable(false);

        jtfNombre.setEditable(false);

        jtfFechaCreacion.setEditable(false);

        jtfEstado.setEditable(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnDarDeBaja.setText("Dar de baja");
        btnDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeBajaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(jtfIDEquipo)
                                    .addComponent(jtfIDProyecto)
                                    .addComponent(jtfFechaCreacion)
                                    .addComponent(jtfEstado))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDarDeBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIDEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIDProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtfFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarDeBaja))
                .addGap(28, 28, 28)
                .addComponent(btnLimpiar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(isANumber(jtfIDEquipo.getText())){
            LineBorder borde = new LineBorder(Color.GRAY);
            jtfIDEquipo.setBorder(borde);
            Equipo equipo = ed.buscarEquipoPorId(Integer.parseInt(jtfIDEquipo.getText()));
            if(equipo.getNombre() != null){
                jtfIDProyecto.setText(equipo.getProyecto().getIdProyecto()+"");
                jtfNombre.setText(equipo.getNombre());
                jtfFechaCreacion.setText(equipo.getFechaCreacion()+"");
                if(equipo.isEstado()){
                    jtfEstado.setText("Activo");
                }else{
                    jtfEstado.setText("Inactivo");
                }
                btnLimpiar.setEnabled(true);
                btnDarDeBaja.setEnabled(true);
                btnBuscar.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(this,"El equipo no existe");
            }
        }else{
            JOptionPane.showMessageDialog(this,"El campo id equipo debe tener contenido y ser numérico");
            jtfIDEquipo.requestFocus();
            LineBorder borde = new LineBorder(Color.RED);
            jtfIDEquipo.setBorder(borde);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        jtfEstado.setText("");
        jtfFechaCreacion.setText("");
        jtfIDEquipo.setText("");
        jtfIDEquipo.requestFocus();
        jtfIDProyecto.setText("");
        jtfNombre.setText("");
        btnBuscar.setEnabled(true);
        btnDarDeBaja.setEnabled(false);
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeBajaActionPerformed
        // TODO add your handling code here:
//        if(isANumber(jtfIDEquipo.getText())){
//            ed.darDeBajaEquipo(Integer.parseInt(jtfIDEquipo.getText()));
//            Equipo equipo = ed.buscarEquipoPorId(Integer.parseInt(jtfIDEquipo.getText()));
//            jtfIDProyecto.setText(equipo.getProyecto().getIdProyecto()+"");
//            jtfNombre.setText(equipo.getNombre());
//            jtfFechaCreacion.setText(equipo.getFechaCreacion()+"");
//            if(equipo.isEstado()){
//                jtfEstado.setText("Activo");
//            }else{
//                jtfEstado.setText("Inactivo");
//            }
//        }else{
//            JOptionPane.showMessageDialog(this, "El campo es necesario y debe ser un número...");
//        }
        if(isANumber(jtfIDEquipo.getText())){
            ed.darDeBajaEquipo(Integer.parseInt(jtfIDEquipo.getText()));
            btnBuscarActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(this, "El campo es necesario y debe ser un número...");
        }
    }//GEN-LAST:event_btnDarDeBajaActionPerformed
    
    public boolean isANumber(String numero){
        boolean resultado;
        try{
            Integer.parseInt(numero);
            resultado = true;
        }catch(NumberFormatException nfe){
            resultado = false;
        }
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDarDeBaja;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfFechaCreacion;
    private javax.swing.JTextField jtfIDEquipo;
    private javax.swing.JTextField jtfIDProyecto;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
