/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladoras.TareaData;
import javax.swing.table.DefaultTableModel;
import entidades.Tarea;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
/**
 *
 * @author nacho
 */
public class ConsultasDeTareas extends javax.swing.JInternalFrame {
    DefaultTableModel table;
    TareaData td = new TareaData();
    /**
     * Creates new form ConsultasDeTareas
     */
    public ConsultasDeTareas() {
        initComponents();
        btnLimpiar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaDeTareas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtfIdProyecto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcboxEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtfCodigoMiembroEquipo = new javax.swing.JTextField();
        btnBuscarPorIdProyecto = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarPorEstado = new javax.swing.JButton();
        btnBuscarPorMiembroEquipo = new javax.swing.JButton();
        btnBuscarID = new javax.swing.JToggleButton();
        btnBuscarCodigo = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-------------------------------------------------------------------------- CONSULTAS SOBRE TAREAS -----------------------------------------------------------------------");

        tableListaDeTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id tarea", "id miembro equipo", "nombre", "fecha creacion", "fecha cierre", "estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableListaDeTareas);
        if (tableListaDeTareas.getColumnModel().getColumnCount() > 0) {
            tableListaDeTareas.getColumnModel().getColumn(0).setResizable(false);
            tableListaDeTareas.getColumnModel().getColumn(1).setResizable(false);
            tableListaDeTareas.getColumnModel().getColumn(2).setResizable(false);
            tableListaDeTareas.getColumnModel().getColumn(3).setResizable(false);
            tableListaDeTareas.getColumnModel().getColumn(4).setResizable(false);
            tableListaDeTareas.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ID Proyecto:");

        jtfIdProyecto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfIdProyecto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Estado:");

        jcboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En progreso", "Inactiva", "Completada" }));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Código:");

        jtfCodigoMiembroEquipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtfCodigoMiembroEquipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBuscarPorIdProyecto.setText("Buscar por idProyecto");
        btnBuscarPorIdProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIdProyectoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscarPorEstado.setText("Buscar por Estado");
        btnBuscarPorEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorEstadoActionPerformed(evt);
            }
        });

        btnBuscarPorMiembroEquipo.setText("Buscar por Código");
        btnBuscarPorMiembroEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorMiembroEquipoActionPerformed(evt);
            }
        });

        btnBuscarID.setText("buscar id");
        btnBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIDActionPerformed(evt);
            }
        });

        btnBuscarCodigo.setText("buscar código");
        btnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel5.setText("¿No sabes el id del proyecto?");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setText("¿No sabes el código?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarPorIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnBuscarPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnBuscarPorMiembroEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBuscarID)
                                .addGap(68, 68, 68))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel4))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfCodigoMiembroEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jcboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtfIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnBuscarCodigo)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(btnBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigoMiembroEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPorIdProyecto)
                    .addComponent(btnBuscarPorEstado)
                    .addComponent(btnBuscarPorMiembroEquipo)
                    .addComponent(btnLimpiar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPorIdProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIdProyectoActionPerformed
        // TODO add your handling code here:
        LineBorder bordes = new LineBorder(Color.GRAY);
        jtfCodigoMiembroEquipo.setBorder(bordes);
        if(isANumber(jtfIdProyecto.getText()) && !(jtfIdProyecto.getText().equals(""))){
            LineBorder borde = new LineBorder(Color.gray);
            jtfIdProyecto.setBorder(borde);
            int idProyecto = Integer.parseInt(jtfIdProyecto.getText());
            table = (DefaultTableModel) tableListaDeTareas.getModel();
            if(!(td.listaTareasPorIdProyectos(idProyecto).isEmpty())){
                for (Tarea tar : td.listaTareasPorIdProyectos(idProyecto)) {
                    String estado = null;
                    switch(tar.getEstado()){
                        case 0: estado = "Pendiente";break;
                        case 1: estado = "En progreso";break;
                        case 2: estado = "Inactiva";break;
                        case 3: estado = "Completada";break;
                    }
                    table.addRow(new Object[]{tar.getIdTarea(),tar.getMiembroEq().getIdMiembroEq(),tar.getNombre(),tar.getFechaCreacion(),tar.getFechaCierre(),estado});
                }
                btnBuscarPorEstado.setEnabled(false);
                btnBuscarPorMiembroEquipo.setEnabled(false);
                btnBuscarPorIdProyecto.setEnabled(false);
                btnLimpiar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this,"El proyecto no contiene tareas o no existe");
            }
        }else{
            JOptionPane.showMessageDialog(this,"El campo debe ser un número y tener contenido...");
            LineBorder borde = new LineBorder(Color.RED);
            jtfIdProyecto.setBorder(borde);
            jtfIdProyecto.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarPorIdProyectoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        table.setRowCount(0);
        jtfIdProyecto.setText("");
        jtfCodigoMiembroEquipo.setText("");
        btnBuscarPorIdProyecto.setEnabled(true);
        btnBuscarPorEstado.setEnabled(true);
        btnBuscarPorMiembroEquipo.setEnabled(true);
        btnLimpiar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarPorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorEstadoActionPerformed
        // TODO add your handling code here:
        int indice = jcboxEstado.getSelectedIndex();
        table = (DefaultTableModel) tableListaDeTareas.getModel();
        if(!(td.tareasPorEstado(indice).isEmpty())){
            for (Tarea tarea : td.tareasPorEstado(indice)) {
                String estado = null;
                switch(tarea.getEstado()){
                    case 0: estado = "Pendiente";break;
                    case 1: estado = "En progreso";break;
                    case 2: estado = "Inactiva";break;
                    case 3: estado = "Completada";break;
                }
                table.addRow(new Object[]{tarea.getIdTarea(),tarea.getMiembroEq().getIdMiembroEq(),tarea.getNombre(),tarea.getFechaCreacion(),tarea.getFechaCierre(),estado});
                btnBuscarPorEstado.setEnabled(false);
                btnBuscarPorMiembroEquipo.setEnabled(false);
                btnBuscarPorIdProyecto.setEnabled(false);
                btnLimpiar.setEnabled(true);
            }
        }else{
            JOptionPane.showMessageDialog(this,"No existen tareas con ese estado");
        }
    }//GEN-LAST:event_btnBuscarPorEstadoActionPerformed

    private void btnBuscarPorMiembroEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorMiembroEquipoActionPerformed
        // TODO add your handling code here:
        LineBorder bordes = new LineBorder(Color.GRAY);
        jtfIdProyecto.setBorder(bordes);
        if(isANumber(jtfCodigoMiembroEquipo.getText()) && !jtfCodigoMiembroEquipo.getText().equals("")){
            int codigo = Integer.parseInt(jtfCodigoMiembroEquipo.getText());
            table = (DefaultTableModel) tableListaDeTareas.getModel();
            if(!td.listarTareasPorIdMiembroEquipo(codigo).isEmpty()){
                LineBorder borde = new LineBorder(Color.GRAY);
                jtfCodigoMiembroEquipo.setBorder(borde);
                for (Tarea tarea : td.listarTareasPorIdMiembroEquipo(codigo)) {
                    String estado = null;
                    switch(tarea.getEstado()){
                        case 0: estado = "Pendiente";break;
                        case 1: estado = "Pendiente";break;
                        case 2: estado = "Pendiente";break;
                        case 3: estado = "Pendiente";break;
                    }
                    table.addRow(new Object[]{tarea.getIdTarea(),tarea.getMiembroEq().getIdMiembroEq(),tarea.getNombre(),tarea.getFechaCreacion(),tarea.getFechaCierre(),estado});
                    btnBuscarPorEstado.setEnabled(false);
                    btnBuscarPorMiembroEquipo.setEnabled(false);
                    btnBuscarPorIdProyecto.setEnabled(false);
                    btnLimpiar.setEnabled(true);
                }
            }else{
                JOptionPane.showMessageDialog(this, "EL código no existe");
            }
        }else{
            JOptionPane.showMessageDialog(this, "El campo código es necesario y debe ser un número");
            LineBorder borde = new LineBorder(Color.RED);
            jtfCodigoMiembroEquipo.setBorder(borde);
            jtfCodigoMiembroEquipo.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarPorMiembroEquipoActionPerformed

    private void btnBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIDActionPerformed
        // TODO add your handling code here:
        ListaDeProyectosVista ldpv = new ListaDeProyectosVista();
        ListaDeProyectosVista.btnVolver.setEnabled(false);
        ldpv.setVisible(true);
        MenuVista.escritorio.add(ldpv);
        ldpv.moveToFront();
    }//GEN-LAST:event_btnBuscarIDActionPerformed

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        // TODO add your handling code here:
        ListaDeTareasVista ldtv = new ListaDeTareasVista();
        ListaDeTareasVista.btnVolverListaDeTareas.setEnabled(false);
        ldtv.setVisible(true);
        MenuVista.escritorio.add(ldtv);
        ldtv.moveToFront();
    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    public boolean isANumber(String numero){
        boolean resultado;
        try{
            Integer.parseInt(numero);
            resultado = true;
        }catch(NumberFormatException nfe){
            resultado = false;
        }
        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscarCodigo;
    private javax.swing.JToggleButton btnBuscarID;
    private javax.swing.JButton btnBuscarPorEstado;
    private javax.swing.JButton btnBuscarPorIdProyecto;
    private javax.swing.JButton btnBuscarPorMiembroEquipo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcboxEstado;
    private javax.swing.JTextField jtfCodigoMiembroEquipo;
    private javax.swing.JTextField jtfIdProyecto;
    private javax.swing.JTable tableListaDeTareas;
    // End of variables declaration//GEN-END:variables
}
