/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.toedter.calendar.JTextFieldDateEditor;
import controladoras.EquipoData;
import controladoras.MiembroData;
import controladoras.MiembrosEquipoData;
import controladoras.TareaData;
import entidades.Equipo;
import entidades.Miembro;
import entidades.MiembrosEquipo;
import entidades.Proyecto;
import entidades.Tarea;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isma
 */
public class MiembrosEquipoVista extends javax.swing.JInternalFrame {

    private EquipoData ed = new EquipoData();
    private MiembroData md = new MiembroData();
    private MiembrosEquipoData med = new MiembrosEquipoData();
    private TareaData td = new TareaData();
    private DefaultTableModel miembrosTableModel;
    private DefaultTableModel equiposTableModel;

    /**
     * Creates new form MiembrosEquipoVista
     */
    public MiembrosEquipoVista() {
        initComponents();
        listarTablaEquipos();
        listarTablaMiembros();
        JTextFieldDateEditor tfFecha = (JTextFieldDateEditor) jdcFechaIncorporacion.getDateEditor();
        tfFecha.setEditable(false);
    }

    private void listarTablaEquipos() {
        equiposTableModel = (DefaultTableModel) jtEquipos.getModel();
        equiposTableModel.setRowCount(0);
        
//        List<MiembrosEquipo> miembrosEquipos = med.listarTodosMiembrosEquipos();

        for (Equipo eq : ed.listarEquipos()) {
            String estado;
            if(eq.isEstado()){
                estado = "Activo";
            }else{
                estado = "Inactivo";
            }
            equiposTableModel.addRow(new Object[]{
                eq.getProyecto(), eq.getNombre(), eq.getFechaCreacion(), estado
            });
        }
    }

    private void listarTablaMiembros() {
        miembrosTableModel = (DefaultTableModel) jtMiembros.getModel();
        miembrosTableModel.setRowCount(0);

        List<Miembro> miembros = md.listarMiembros();

        for (Miembro miembro : miembros) {
            String estado;
            if(miembro.isEstado()){
                estado = "Activo";
            }else{
                estado = "Inactivo";
            }
            miembrosTableModel.addRow(new Object[]{
                miembro.getNombre(),
                miembro.getApellido(),
                miembro.getDni(),
                estado
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEquipos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMiembros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdcFechaIncorporacion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setPreferredSize(new java.awt.Dimension(1000, 550));

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jtEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROYECTO", "NOMBRE", "FECHA CREACION", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtEquipos);
        if (jtEquipos.getColumnModel().getColumnCount() > 0) {
            jtEquipos.getColumnModel().getColumn(0).setResizable(false);
            jtEquipos.getColumnModel().getColumn(1).setResizable(false);
            jtEquipos.getColumnModel().getColumn(2).setResizable(false);
            jtEquipos.getColumnModel().getColumn(3).setResizable(false);
        }

        jtMiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDO", "DNI", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtMiembros);

        jLabel1.setText("LISTAR MIEMBROS Y EQUIPOS - ASIGNAR O QUITAR MIEMBROS A UN EQUIPO");

        btnAsignar.setText("ASIGNAR");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        jLabel2.setText("LISTA DE MIEMBROS");

        jLabel3.setText("LISTA DE EQUIPOS");

        jLabel4.setText("Fecha de incorporacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jdcFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jdcFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnAsignar)))
                .addGap(59, 59, 59)
                .addComponent(btnSalir)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        int fila = jtMiembros.getSelectedRow();
        int filaEquipo = jtEquipos.getSelectedRow();
        LocalDate fechaIncorporacion = jdcFechaIncorporacion.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        MiembrosEquipo miembrosEquipo = new MiembrosEquipo();
        Proyecto pro  = (Proyecto) equiposTableModel.getValueAt(fila, 0);
        Miembro miembro = md.buscarMiembroPorDni(Integer.parseInt(miembrosTableModel.getValueAt(fila, 2)+""));
        Equipo equipo = ed.buscarEquipoPorProyecto(pro.getIdProyecto());
        miembrosEquipo.setMiembro(miembro);
        miembrosEquipo.setEquipo(equipo);
        miembrosEquipo.setFechaIncorporacion(fechaIncorporacion);
        med.crearMiembrosEquipo(miembrosEquipo);
    }//GEN-LAST:event_btnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFechaIncorporacion;
    private javax.swing.JTable jtEquipos;
    private javax.swing.JTable jtMiembros;
    // End of variables declaration//GEN-END:variables
}
