/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import controladoras.ProyectoData;
import entidades.Proyecto;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author TECNOVENTAS
 */
public class ModificarProyectoVista extends javax.swing.JInternalFrame {
    int idProyectoSeleccionado=-1;

    /**
     * Creates new form ModificarProyecto
     */
    public ModificarProyectoVista() {
        initComponents();
        btngEstadoProyecto.add(jrbEstadoActivo);
        btngEstadoProyecto.add(jrbEstadoInactivo);
        btnBuscar.setEnabled(false);
        btnActualizar.setEnabled(false);
        armarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngEstadoProyecto = new javax.swing.ButtonGroup();
        jlTitulo = new javax.swing.JLabel();
        jlIdProyecto = new javax.swing.JLabel();
        jtfIdProyecto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jlNombreProyecto = new javax.swing.JLabel();
        jtfNombreProyecto = new javax.swing.JTextField();
        jlDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        jlEstadoProyecto = new javax.swing.JLabel();
        jrbEstadoActivo = new javax.swing.JRadioButton();
        jrbEstadoInactivo = new javax.swing.JRadioButton();
        jlFechaInicio = new javax.swing.JLabel();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jComboProy = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jlTitulo.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jlTitulo.setText("Modificar datos del Proyecto");

        jlIdProyecto.setText("ID DE PROYECTO:");

        jtfIdProyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfIdProyectoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdProyectoKeyTyped(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jlNombreProyecto.setText("NOMBRE PROYECTO:");

        jlDescripcion.setText("DESCRIPCION:");

        jtaDescripcion.setColumns(20);
        jtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtaDescripcion);

        jlEstadoProyecto.setText("ESTADO DE PROYECTO:");

        jrbEstadoActivo.setText("ACTIVO");

        jrbEstadoInactivo.setText("INACTIVO");

        jlFechaInicio.setText("FECHA DE INICIO:");

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jComboProy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboProyMouseClicked(evt);
            }
        });

        jLabel1.setText("PROYECTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlEstadoProyecto)
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbEstadoActivo)
                                .addGap(75, 75, 75)
                                .addComponent(jrbEstadoInactivo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlIdProyecto)
                            .addComponent(jlNombreProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlDescripcion)
                            .addComponent(jlFechaInicio)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboProy, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtfNombreProyecto)
                            .addComponent(jScrollPane1)
                            .addComponent(jdcFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlTitulo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboProy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdProyecto)
                    .addComponent(jtfIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreProyecto)
                    .addComponent(jtfNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFechaInicio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbEstadoActivo)
                    .addComponent(jrbEstadoInactivo)
                    .addComponent(jlEstadoProyecto))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnActualizar)
                    .addComponent(btnNuevo))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void armarCombo(){
        ProyectoData pd = new ProyectoData();
        ArrayList<Proyecto> listaProy = new ArrayList();
        
        listaProy= pd.listarProyectos();
        if (!listaProy.isEmpty()){
            for(Proyecto unProyecto:listaProy ){
                //jComboProy.addItem(unProyecto.getIdProyecto()+" - "+unProyecto.getNombre());
                jComboProy.addItem(unProyecto);
            }            
        }                
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        Proyecto proyecto = new Proyecto();
        ProyectoData pd = new ProyectoData();
        proyecto = pd.buscarProyecto(parseInt(jtfIdProyecto.getText()));       
        
        //LocalDate lc = proyecto.getFechaInicio();
        //java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
        
        if(proyecto != null){
            LocalDate lc = proyecto.getFechaInicio();
            java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
            jtfNombreProyecto.setText(proyecto.getNombre());
            jtaDescripcion.setText(proyecto.getDescripcion());
            jdcFechaInicio.setDate(date);
            jrbEstadoActivo.setEnabled(true);
            jrbEstadoInactivo.setEnabled(true);
            if (proyecto.isEstado()){      
                jrbEstadoActivo.setSelected(true);
            }else{      
                jrbEstadoInactivo.setSelected(true);
            }        
            btnActualizar.setEnabled(true);
        } //else{
           // JOptionPane.showMessageDialog(null, "Proyecto no encontrado");
       // } 
    }                                         
    private void jComboProyMouseClicked(java.awt.event.MouseEvent evt) {
        Proyecto proyecto = new Proyecto();
        ProyectoData pd = new ProyectoData();
        proyecto= (Proyecto) jComboProy.getSelectedItem();
        proyecto = pd.buscarProyecto(proyecto.getIdProyecto());       
        
        //LocalDate lc = proyecto.getFechaInicio();
        //java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
        
        if(proyecto != null){
            LocalDate lc = proyecto.getFechaInicio();
            java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
            jtfNombreProyecto.setText(proyecto.getNombre());
            jtaDescripcion.setText(proyecto.getDescripcion());
            jdcFechaInicio.setDate(date);
            jrbEstadoActivo.setEnabled(true);
            jrbEstadoInactivo.setEnabled(true);
            if (proyecto.isEstado()){      
                jrbEstadoActivo.setSelected(true);
            }else{      
                jrbEstadoInactivo.setSelected(true);
            }        
            btnActualizar.setEnabled(true);
        }

    } 
    
    
    
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        java.util.Date fecha = jdcFechaInicio.getDate();
        LocalDate inicio = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Proyecto proyecto = new Proyecto();
        ProyectoData pd = new ProyectoData();
        if(!jtfIdProyecto.getText().equals("")){
            if (!jtfIdProyecto.getText().isEmpty()){
                proyecto.setIdProyecto(parseInt(jtfIdProyecto.getText()));
            }else{
                JOptionPane.showMessageDialog(this, "El campo Id del Proyecto es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jtfNombreProyecto.getText().isEmpty()) {
                proyecto.setNombre(jtfNombreProyecto.getText());
            }else{            
                JOptionPane.showMessageDialog(this, "El campo Nombre del Proyecto es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jtaDescripcion.getText().isEmpty()) {
                proyecto.setDescripcion(jtaDescripcion.getText());        
            }else{
                JOptionPane.showMessageDialog(this, "El campo Descripción es obligatorio", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            if (fecha != null) {
                proyecto.setFechaInicio(inicio);
            }else{
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de inicio válida", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jrbEstadoActivo.isSelected() && !jrbEstadoInactivo.isSelected()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un estado para el proyecto", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(jrbEstadoActivo.isSelected()){
                pd.activarProyecto(parseInt(jtfIdProyecto.getText()));        
            }else{
                pd.inactivarProyecto(parseInt(jtfIdProyecto.getText())); 
            }
            pd.modificarDatosProyecto(proyecto);
        }else{
            JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                             

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        dispose();
    }                                        

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jtfNombreProyecto.setText("");
        jtaDescripcion.setText("");
        jdcFechaInicio.setDate(null);
        btngEstadoProyecto.clearSelection();
        jtfIdProyecto.setText("");
        btnActualizar.setEnabled(false);
        btnBuscar.setEnabled(false);
    }                                        

    private void jtfIdProyectoKeyReleased(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
        habilitarBotonBuscar();
    }                                         

    private void jtfIdProyectoKeyTyped(java.awt.event.KeyEvent evt) {                                       
        // TODO add your handling code here:
        int key = evt.getKeyChar();

         boolean numeros = key >= 48 && key <= 57;
        
        if (!numeros)
              {
                 evt.consume();
                     } 
    }                                      
    
    public void habilitarBotonBuscar(){
        if (!jtfIdProyecto.getText().isEmpty()){
            btnBuscar.setEnabled(true);
        }
    }
    /*
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Proyecto proyecto = new Proyecto();
        ProyectoData pd = new ProyectoData();
        proyecto = pd.buscarProyecto(parseInt(jtfIdProyecto.getText()));       
        
        LocalDate lc = proyecto.getFechaInicio();
        java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
        
        if(proyecto != null){
            jtfNombreProyecto.setText(proyecto.getNombre());
            jtaDescripcion.setText(proyecto.getDescripcion());
            jdcFechaInicio.setDate(date);
            jrbEstadoActivo.setEnabled(true);
            jrbEstadoInactivo.setEnabled(true);
            if (proyecto.isEstado()){      
                jrbEstadoActivo.setSelected(true);
            }else{      
                jrbEstadoInactivo.setSelected(true);
            }        
        } else{
            JOptionPane.showMessageDialog(null, "Proyecto no encontrado");
        } 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        java.util.Date fecha = jdcFechaInicio.getDate();
        LocalDate inicio = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Proyecto proyecto = new Proyecto();
        ProyectoData pd = new ProyectoData();
        if(!jtfIdProyecto.getText().equals("")){
            if (!jtfIdProyecto.getText().isEmpty()){
                proyecto.setIdProyecto(parseInt(jtfIdProyecto.getText()));
            }else{
                JOptionPane.showMessageDialog(this, "El campo Id del Proyecto es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jtfNombreProyecto.getText().isEmpty()) {
                proyecto.setNombre(jtfNombreProyecto.getText());
            }else{            
                JOptionPane.showMessageDialog(this, "El campo Nombre del Proyecto es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jtaDescripcion.getText().isEmpty()) {
                proyecto.setDescripcion(jtaDescripcion.getText());        
            }else{
                JOptionPane.showMessageDialog(this, "El campo Descripción es obligatorio", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            if (fecha != null) {
                proyecto.setFechaInicio(inicio);
            }else{
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de inicio válida", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jrbEstadoActivo.isSelected() && !jrbEstadoInactivo.isSelected()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un estado para el proyecto", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(jrbEstadoActivo.isSelected()){
                pd.activarProyecto(parseInt(jtfIdProyecto.getText()));        
            }else{
                pd.inactivarProyecto(parseInt(jtfIdProyecto.getText())); 
            }
            pd.modificarDatosProyecto(proyecto);
        }else{
            JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        jtfNombreProyecto.setText("");
        jtaDescripcion.setText("");
        jdcFechaInicio.setDate(null);
        btngEstadoProyecto.clearSelection();
        jtfIdProyecto.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jtfIdProyectoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdProyectoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdProyectoKeyReleased

    private void jtfIdProyectoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdProyectoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdProyectoKeyTyped

    private void jComboProyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboProyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProyMouseClicked
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup btngEstadoProyecto;
    private javax.swing.JComboBox<Proyecto> jComboProy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFechaInicio;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlEstadoProyecto;
    private javax.swing.JLabel jlFechaInicio;
    private javax.swing.JLabel jlIdProyecto;
    private javax.swing.JLabel jlNombreProyecto;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JRadioButton jrbEstadoActivo;
    private javax.swing.JRadioButton jrbEstadoInactivo;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JTextField jtfIdProyecto;
    private javax.swing.JTextField jtfNombreProyecto;
    // End of variables declaration//GEN-END:variables
}
