/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import controladoras.MiembroData;
import entidades.Miembro;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author TECNOVENTAS
 */
public class ModificarMiembroVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarMiembroVista
     */
    public ModificarMiembroVista() {
        initComponents();
        btngEstadoMiembro.add(jrbEstadoActivo);
        btngEstadoMiembro.add(jrbEstadoInactivo);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngEstadoMiembro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jlIdMiembro = new javax.swing.JLabel();
        jtfIdMiembro = new javax.swing.JTextField();
        btnBuscarId = new javax.swing.JButton();
        jlDni = new javax.swing.JLabel();
        jtfDniMiembro = new javax.swing.JTextField();
        btnBuscarDni = new javax.swing.JButton();
        jlNombreMiembro = new javax.swing.JLabel();
        jtfNombreMiembro = new javax.swing.JTextField();
        jlApellidoMiembro = new javax.swing.JLabel();
        jtfApellidoMiembro = new javax.swing.JTextField();
        jlEstadoMiembro = new javax.swing.JLabel();
        jrbEstadoActivo = new javax.swing.JRadioButton();
        jrbEstadoInactivo = new javax.swing.JRadioButton();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setText("Modificar Datos de un Miembro");

        jlIdMiembro.setText("ID DE MIEMBRO:");

        btnBuscarId.setText("BUSCAR");
        btnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdActionPerformed(evt);
            }
        });

        jlDni.setText("DNI:");

        btnBuscarDni.setText("BUSCAR");
        btnBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDniActionPerformed(evt);
            }
        });

        jlNombreMiembro.setText("NOMBRE:");

        jlApellidoMiembro.setText("APELLIDO:");

        jlEstadoMiembro.setText("ESTADO:");

        jrbEstadoActivo.setText("Miembro Activo");

        jrbEstadoInactivo.setText("Miembro Inactivo");

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlIdMiembro)
                                    .addComponent(jlDni)
                                    .addComponent(jlNombreMiembro)
                                    .addComponent(jlApellidoMiembro)
                                    .addComponent(jlEstadoMiembro))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbEstadoActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                        .addComponent(jrbEstadoInactivo))
                                    .addComponent(jtfIdMiembro)
                                    .addComponent(jtfDniMiembro)
                                    .addComponent(jtfNombreMiembro)
                                    .addComponent(jtfApellidoMiembro))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarId, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btnBuscarDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdMiembro)
                    .addComponent(jtfIdMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(jtfDniMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreMiembro)
                    .addComponent(jtfNombreMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellidoMiembro)
                    .addComponent(jtfApellidoMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstadoMiembro)
                    .addComponent(jrbEstadoActivo)
                    .addComponent(jrbEstadoInactivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnActualizar)
                    .addComponent(btnNuevo))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdActionPerformed
        // TODO add your handling code here:
        Miembro miembro = new Miembro();
        MiembroData md = new MiembroData();
        miembro = md.buscarMiembroPorId(parseInt(jtfIdMiembro.getText()));
        if(miembro != null){
            jtfDniMiembro.setText(String.valueOf(miembro.getDni()));
            jtfNombreMiembro.setText(miembro.getNombre());
            jtfApellidoMiembro.setText(miembro.getApellido());          
            jrbEstadoActivo.setEnabled(true);
            jrbEstadoInactivo.setEnabled(true);
            if (miembro.isEstado()){      
                jrbEstadoActivo.setSelected(true);
            }else{      
                jrbEstadoInactivo.setSelected(true);
            }        
        } else{
            JOptionPane.showMessageDialog(null, "Miembro no encontrado");
        }
    }//GEN-LAST:event_btnBuscarIdActionPerformed

    private void btnBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDniActionPerformed
        // TODO add your handling code here:
        Miembro miembro = new Miembro();
        MiembroData md = new MiembroData();
        miembro = md.buscarMiembroPorDni(parseInt(jtfDniMiembro.getText()));
        if(miembro != null){
            jtfIdMiembro.setText(String.valueOf(miembro.getIdMiembro()));
            jtfNombreMiembro.setText(miembro.getNombre());
            jtfApellidoMiembro.setText(miembro.getApellido());          
            jrbEstadoActivo.setEnabled(true);
            jrbEstadoInactivo.setEnabled(true);
            if (miembro.isEstado()){      
                jrbEstadoActivo.setSelected(true);
            }else{      
                jrbEstadoInactivo.setSelected(true);
            }        
        } else{
            JOptionPane.showMessageDialog(null, "Miembro no encontrado");
        }
    }//GEN-LAST:event_btnBuscarDniActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        Miembro miembro = new Miembro();
        MiembroData md = new MiembroData();
        if(!jtfIdMiembro.getText().equals("")){
            if (!jtfIdMiembro.getText().isEmpty()){
                miembro.setIdMiembro(parseInt(jtfIdMiembro.getText()));
            }else{
                JOptionPane.showMessageDialog(this, "El campo Id del miembro es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jtfNombreMiembro.getText().isEmpty()) {
                miembro.setNombre(jtfNombreMiembro.getText());
            }else{            
                JOptionPane.showMessageDialog(this, "El campo Nombre del miembro es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (!jtfApellidoMiembro.getText().isEmpty()) {
                miembro.setApellido(jtfApellidoMiembro.getText());        
            }else{
                JOptionPane.showMessageDialog(this, "El campo Apellido del miembro es obligatorio", "Error", JOptionPane.ERROR_MESSAGE); 
            }
            if (jtfDniMiembro.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "El campo DNI del miembro es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);  
            }else{
                miembro.setDni(parseInt(jtfDniMiembro.getText()));
            }
            if (!jrbEstadoActivo.isSelected() && !jrbEstadoInactivo.isSelected()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un estado para el miembro", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(jrbEstadoActivo.isSelected()){
                md.activarMiembro(parseInt(jtfIdMiembro.getText()));        
            }else{
                md.inactivarMiembro(parseInt(jtfIdMiembro.getText())); 
            }
            md.modificarDatosMiembro(miembro);
        }else{
            JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        jtfIdMiembro.setText("");
        jtfDniMiembro.setText("");
        jtfNombreMiembro.setText("");
        jtfApellidoMiembro.setText("");       
        btngEstadoMiembro.clearSelection();
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup btngEstadoMiembro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlApellidoMiembro;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlEstadoMiembro;
    private javax.swing.JLabel jlIdMiembro;
    private javax.swing.JLabel jlNombreMiembro;
    private javax.swing.JRadioButton jrbEstadoActivo;
    private javax.swing.JRadioButton jrbEstadoInactivo;
    private javax.swing.JTextField jtfApellidoMiembro;
    private javax.swing.JTextField jtfDniMiembro;
    private javax.swing.JTextField jtfIdMiembro;
    private javax.swing.JTextField jtfNombreMiembro;
    // End of variables declaration//GEN-END:variables
}
