/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.toedter.calendar.JTextFieldDateEditor;
import controladoras.ComentariosData;
import controladoras.MiembrosEquipoData;
import controladoras.ProyectoData;
import controladoras.TareaData;
import entidades.MiembrosEquipo;
import entidades.Proyecto;
import entidades.Comentarios;
import entidades.Tarea;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nacho
 */
public class TareasListasVista extends javax.swing.JInternalFrame {

    private DefaultTableModel table;
    private DefaultTableModel tableComentarios;
    /**
     * Creates new form ModificarTareaVista
     */
    public TareasListasVista() {
        initComponents();
        initTable();
        initComboEquipos();
        initComboProyectos();
        tableListaDeTareas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JFormattedTextField textFCreacion = (JFormattedTextField) jdcFechaCreacion.getDateEditor().getUiComponent();
        textFCreacion.setEditable(false);
        JFormattedTextField textFCierre = (JFormattedTextField) jdcFechaCierre.getDateEditor().getUiComponent();
        textFCierre.setEditable(false);
        jcboxEstado.setEnabled(false);
        btnModificar.setEnabled(false);
        btnCambiarEstado.setEnabled(false);
        btnGuardarModificaciones.setEnabled(false);
        btnGuardarCambioDeEstado.setEnabled(false);
        jdcFechaCreacion.getCalendarButton().setEnabled(false);
        jdcFechaCierre.getCalendarButton().setEnabled(false);
        btnVerComentariosTareaSeleccionada.setEnabled(false);
        txtAreaComentario.setEditable(false);
        jdcFechaAvanceComentarios.getCalendarButton().setEnabled(true);
        btnModificarComentario.setEnabled(false);
        JTextFieldDateEditor textFieldFechaAvance = (JTextFieldDateEditor) jdcFechaAvanceComentarios.getDateEditor();
        textFieldFechaAvance.setEditable(false);
        btnAgregarComentario.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jdcFechaCreacion = new com.toedter.calendar.JDateChooser();
        jdcFechaCierre = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jcboxEstado = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaDeTareas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcboxPorEstado = new javax.swing.JComboBox<>();
        jcboxPorEquipos = new javax.swing.JComboBox<>();
        jcboxPorProyectos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCambiarEstado = new javax.swing.JButton();
        btnGuardarModificaciones = new javax.swing.JButton();
        btnGuardarCambioDeEstado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVerComentariosTareaSeleccionada = new javax.swing.JButton();
        btnAgregarComentario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaComentario = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableComentariosSobreTareas = new javax.swing.JTable();
        jdcFechaAvanceComentarios = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btnModificarComentario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("NOMBRE");

        jLabel3.setText("FECHA CREACION");

        jLabel4.setText("FECHA CIERRE");

        jtfNombre.setEditable(false);

        jLabel6.setText("ESTADO");

        jcboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En progreso", "Inactiva", "Completada" }));

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tableListaDeTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tarea", "empleado", "nombre", "fecha creacion", "fecha cierre", "estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListaDeTareas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListaDeTareasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListaDeTareas);
        if (tableListaDeTareas.getColumnModel().getColumnCount() > 0) {
            tableListaDeTareas.getColumnModel().getColumn(0).setMinWidth(70);
            tableListaDeTareas.getColumnModel().getColumn(0).setMaxWidth(70);
            tableListaDeTareas.getColumnModel().getColumn(1).setMinWidth(70);
            tableListaDeTareas.getColumnModel().getColumn(1).setMaxWidth(70);
            tableListaDeTareas.getColumnModel().getColumn(2).setResizable(false);
            tableListaDeTareas.getColumnModel().getColumn(3).setMinWidth(100);
            tableListaDeTareas.getColumnModel().getColumn(3).setMaxWidth(100);
            tableListaDeTareas.getColumnModel().getColumn(4).setMinWidth(100);
            tableListaDeTareas.getColumnModel().getColumn(4).setMaxWidth(100);
            tableListaDeTareas.getColumnModel().getColumn(5).setMinWidth(100);
            tableListaDeTareas.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("LISTA DE TAREAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(543, 543, 543))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcboxPorEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En progreso", "Inactiva", "Completada" }));
        jcboxPorEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxPorEstadoActionPerformed(evt);
            }
        });

        jcboxPorEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxPorEquiposActionPerformed(evt);
            }
        });

        jcboxPorProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxPorProyectosActionPerformed(evt);
            }
        });

        jLabel9.setText("Por estado");

        jLabel10.setText("Por equipos");

        jLabel11.setText("Por proyectos");

        btnCambiarEstado.setText("Cambiar Estado");
        btnCambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstadoActionPerformed(evt);
            }
        });

        btnGuardarModificaciones.setText("Guardar");
        btnGuardarModificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModificacionesActionPerformed(evt);
            }
        });

        btnGuardarCambioDeEstado.setText("Guardar");
        btnGuardarCambioDeEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambioDeEstadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione una fila de la tabla para modificar");

        btnVerComentariosTareaSeleccionada.setText("Ver comentarios");
        btnVerComentariosTareaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerComentariosTareaSeleccionadaActionPerformed(evt);
            }
        });

        btnAgregarComentario.setText("Agregar comentario");
        btnAgregarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComentarioActionPerformed(evt);
            }
        });

        txtAreaComentario.setColumns(20);
        txtAreaComentario.setRows(5);
        jScrollPane2.setViewportView(txtAreaComentario);

        tableComentariosSobreTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numero", "tarea", "comentario", "fechaAvance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableComentariosSobreTareas);
        if (tableComentariosSobreTareas.getColumnModel().getColumnCount() > 0) {
            tableComentariosSobreTareas.getColumnModel().getColumn(0).setMinWidth(60);
            tableComentariosSobreTareas.getColumnModel().getColumn(0).setMaxWidth(60);
            tableComentariosSobreTareas.getColumnModel().getColumn(1).setMinWidth(60);
            tableComentariosSobreTareas.getColumnModel().getColumn(1).setMaxWidth(60);
            tableComentariosSobreTareas.getColumnModel().getColumn(2).setResizable(false);
            tableComentariosSobreTareas.getColumnModel().getColumn(3).setMinWidth(100);
            tableComentariosSobreTareas.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jLabel7.setText("Fecha avance");

        btnModificarComentario.setText("Modificar");
        btnModificarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarComentarioActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("seleccione un comentario a modificar");

        jButton1.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardarModificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCambiarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardarCambioDeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jdcFechaCierre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jdcFechaCreacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerComentariosTareaSeleccionada)
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(jLabel9)
                                        .addGap(184, 184, 184)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(jcboxPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(jcboxPorEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jcboxPorProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnAgregarComentario)))
                        .addGap(69, 69, 69))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnModificarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jdcFechaAvanceComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcboxPorProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcboxPorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcboxPorEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerComentariosTareaSeleccionada)
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnAgregarComentario)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdcFechaAvanceComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btnModificarComentario)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcFechaCierre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnCambiarEstado)
                            .addComponent(btnSalir))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarCambioDeEstado)
                            .addComponent(btnGuardarModificaciones))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        jtfNombre.setEditable(true);
        jdcFechaCreacion.getCalendarButton().setEnabled(true);
        jdcFechaCierre.getCalendarButton().setEnabled(true);
        btnGuardarModificaciones.setEnabled(true);
        btnModificar.setEnabled(false);
        btnCambiarEstado.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jcboxPorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxPorEstadoActionPerformed
        // TODO add your handling code here:
        TareaData td = new TareaData();
        int estado = jcboxPorEstado.getSelectedIndex();
        table.setRowCount(0);
        for (Tarea tar : td.tareasPorEstado(estado)) {
            String estado1 = null;
            switch(tar.getEstado()){
                case 0: estado1 = "Pendiente";break;
                case 1: estado1 = "En Progreso";break;
                case 2: estado1 = "Inactiva";break;
                case 3: estado1 = "Completada";break;
            }
            table.addRow(new Object[]{tar.getIdTarea(), tar.getMiembroEq().getIdMiembroEq(), tar.getNombre(), tar.getFechaCreacion(), tar.getFechaCierre(), estado1});
        }
    }//GEN-LAST:event_jcboxPorEstadoActionPerformed

    private void jcboxPorEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxPorEquiposActionPerformed
        // TODO add your handling code here:
        table.setRowCount(0);
        TareaData td = new TareaData();
        MiembrosEquipo me = (MiembrosEquipo) jcboxPorEquipos.getSelectedItem();
        for (Tarea tar : td.listarTareasPorIdMiembroEquipo(me.getIdMiembroEq())) {
            String estado = null;
            switch(tar.getEstado()){
                case 0: estado = "Pendiente";break;
                case 1: estado = "En Progreso";break;
                case 2: estado = "Inactiva";break;
                case 3: estado = "Completada";break;
            }
            table.addRow(new Object[]{tar.getIdTarea(), tar.getMiembroEq().getIdMiembroEq(), tar.getNombre(), tar.getFechaCreacion(), tar.getFechaCierre(),estado});
        }
    }//GEN-LAST:event_jcboxPorEquiposActionPerformed

    private void jcboxPorProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxPorProyectosActionPerformed
        // TODO add your handling code here:
        table.setRowCount(0);
        TareaData td = new TareaData();
        Proyecto pr = (Proyecto) jcboxPorProyectos.getSelectedItem();
        for (Tarea tar : td.listaTareasPorIdProyectos(pr.getIdProyecto())) {
            String estado = null;
            switch(tar.getEstado()){
                case 0: estado = "Pendiente";break;
                case 1: estado = "En Progreso";break;
                case 2: estado = "Inactiva";break;
                case 3: estado = "Completada";break;
            }
            table.addRow(new Object[]{tar.getIdTarea(), tar.getMiembroEq().getIdMiembroEq(), tar.getNombre(), tar.getFechaCreacion(), tar.getFechaCierre(), estado});
        }
    }//GEN-LAST:event_jcboxPorProyectosActionPerformed

    private void tableListaDeTareasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListaDeTareasMouseClicked
        // TODO add your handling code here:
        int fila = tableListaDeTareas.getSelectedRow();
        jtfNombre.setText(table.getValueAt(fila, 2).toString());
        jdcFechaCreacion.setDate(Date.valueOf(table.getValueAt(fila, 3).toString()));
        jdcFechaCierre.setDate(Date.valueOf(table.getValueAt(fila,4).toString()));
        int indice;
        if(table.getValueAt(fila, 5).toString().equalsIgnoreCase("pendiente")){
            indice = 0;
        }else if(table.getValueAt(fila, 5).toString().equalsIgnoreCase("en progreso")){
            indice = 1;
        }else if(table.getValueAt(fila, 5).toString().equalsIgnoreCase("Inactiva")){
            indice = 2;
        }else{
            indice = 3;
        }
        btnVerComentariosTareaSeleccionada.setEnabled(true);
        jcboxEstado.setSelectedIndex(indice);
        jdcFechaCreacion.getCalendarButton().setEnabled(false);
        jdcFechaCierre.getCalendarButton().setEnabled(false);
        btnModificar.setEnabled(true);
        jcboxEstado.setEnabled(false);
        btnCambiarEstado.setEnabled(true);
        btnGuardarCambioDeEstado.setEnabled(false);
        btnGuardarModificaciones.setEnabled(false);
        jtfNombre.setEditable(false);
        txtAreaComentario.setEditable(false);
//        jdcFechaAvanceComentarios.getCalendarButton().setEnabled(true);
        btnModificarComentario.setEnabled(false);
        btnAgregarComentario.setEnabled(true);
    }//GEN-LAST:event_tableListaDeTareasMouseClicked

    private void btnGuardarModificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModificacionesActionPerformed
        // TODO add your handling code here:
        TareaData td = new TareaData();
        int fila = tableListaDeTareas.getSelectedRow();
        String idTarea = (table.getValueAt(fila, 0)+"");
        String idMiembroEquipo = (table.getValueAt(fila, 1)+"");
        if(jtfNombre.getText().equals("")){
            JOptionPane.showMessageDialog(this,"El campo nombre debe estar completo");
            jtfNombre.requestFocus();
        }else if(jdcFechaCreacion.getDate() == null){
            JOptionPane.showMessageDialog(this,"El campo fecha creacion no debe estar nulo");
            jdcFechaCreacion.requestFocus();
        }else if(jdcFechaCierre.getDate() == null){
            JOptionPane.showMessageDialog(this,"El campo fecha cierre no debe estar nulo");
            jdcFechaCierre.requestFocus();
        }else{
            String nombre = jtfNombre.getText();
            LocalDate fechaCreacion = jdcFechaCreacion.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaCierre = jdcFechaCierre.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int estado = jcboxEstado.getSelectedIndex();
            MiembrosEquipo miembroequipo =  new MiembrosEquipoData().buscarMiembrosEquipoPorId(Integer.parseInt(idMiembroEquipo));
            if(miembroequipo == null){
                JOptionPane.showMessageDialog(this,"El código no existe...");
            }else{
                Tarea tarea = new Tarea(Integer.parseInt(idTarea), miembroequipo, nombre, fechaCreacion, fechaCierre, estado);
                td.modificarTarea(tarea);
                table.setValueAt(nombre, fila, 2);
                table.setValueAt(fechaCreacion, fila, 3);
                table.setValueAt(fechaCierre, fila, 4);
                btnGuardarModificaciones.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnGuardarModificacionesActionPerformed

    private void btnCambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstadoActionPerformed
        btnGuardarCambioDeEstado.setEnabled(true);
        jcboxEstado.setEnabled(true);
        btnCambiarEstado.setEnabled(false);
        btnModificar.setEnabled(false);
    }//GEN-LAST:event_btnCambiarEstadoActionPerformed

    private void btnGuardarCambioDeEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambioDeEstadoActionPerformed
        TareaData td = new TareaData();
        int fila = tableListaDeTareas.getSelectedRow();
        int idTarea = Integer.parseInt(table.getValueAt(fila, 0)+"");
        int estado = jcboxEstado.getSelectedIndex();
        td.actualizarEstadoDeLasTareas(idTarea, estado);
        String estado2 = null;
        switch(estado){
            case 0: estado2 = "Pendiente";break;
            case 1: estado2 = "En Progreso";break;
            case 2: estado2 = "Inactiva";break;
            case 3: estado2 = "Completada";break;
        }
        table.setValueAt(estado2, fila, 5);
        btnGuardarCambioDeEstado.setEnabled(false);
    }//GEN-LAST:event_btnGuardarCambioDeEstadoActionPerformed

    private void btnVerComentariosTareaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerComentariosTareaSeleccionadaActionPerformed
        // TODO add your handling code here:
        tableComentarios = (DefaultTableModel) tableComentariosSobreTareas.getModel();
        tableComentarios.setRowCount(0);
        TareaData td = new TareaData();
        ComentariosData cd = new ComentariosData();
        int fila = tableListaDeTareas.getSelectedRow();
        int id = Integer.parseInt(table.getValueAt(fila, 0)+"");
        Tarea tarea = td.buscarTareaXiD(id);
        ArrayList<Comentarios>comentarios= cd.listarComentariosXTarea(tarea);
        if(comentarios.isEmpty()){
            JOptionPane.showMessageDialog(this, "La tarea no contiene comentarios aún...");
        }else{
            for(Comentarios com : comentarios){
                tableComentarios.addRow(new Object[]{com.getIdComentario(), com.getTarea().getIdTarea(), com.getComentario(), com.getFechaAvance()});
            }
        }
    }//GEN-LAST:event_btnVerComentariosTareaSeleccionadaActionPerformed

    private void btnAgregarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComentarioActionPerformed
        txtAreaComentario.setEditable(true);
        txtAreaComentario.requestFocus();
        jdcFechaAvanceComentarios.getCalendarButton().setEnabled(true);
        btnModificarComentario.setEnabled(true);
    }//GEN-LAST:event_btnAgregarComentarioActionPerformed

    private void btnModificarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarComentarioActionPerformed
        // TODO add your handling code here:
        ComentariosData cd = new ComentariosData();
        int fila = tableListaDeTareas.getSelectedRow();
        int idTarea = Integer.parseInt(table.getValueAt(fila, 0)+"");
        String comentario = txtAreaComentario.getText();
        LocalDate fechaAvance = jdcFechaAvanceComentarios.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Comentarios comen = new Comentarios(new TareaData().buscarTareaXiD(idTarea), comentario, fechaAvance);
        cd.crearComentarios(comen);
        btnModificarComentario.setEnabled(false);
        txtAreaComentario.setText("");
        txtAreaComentario.setEditable(false);
        jdcFechaAvanceComentarios.setDate(null);
        jdcFechaAvanceComentarios.setEnabled(true);
        btnModificarComentario.setEnabled(true);
    }//GEN-LAST:event_btnModificarComentarioActionPerformed

    public boolean isANumber(String numero){ //Implemento este metodo para comprobar si un campo es un número o no...
        boolean es;
        try{
            Integer.parseInt(numero);
            es = true;
        }catch(NumberFormatException nfe){
            es = false;
        }
        return es;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarComentario;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnGuardarCambioDeEstado;
    private javax.swing.JButton btnGuardarModificaciones;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarComentario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerComentariosTareaSeleccionada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcboxEstado;
    private javax.swing.JComboBox<MiembrosEquipo> jcboxPorEquipos;
    private javax.swing.JComboBox<String> jcboxPorEstado;
    private javax.swing.JComboBox<Proyecto> jcboxPorProyectos;
    private com.toedter.calendar.JDateChooser jdcFechaAvanceComentarios;
    private com.toedter.calendar.JDateChooser jdcFechaCierre;
    private com.toedter.calendar.JDateChooser jdcFechaCreacion;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTable tableComentariosSobreTareas;
    private javax.swing.JTable tableListaDeTareas;
    private javax.swing.JTextArea txtAreaComentario;
    // End of variables declaration//GEN-END:variables

    private void initTable() {
        TareaData td = new TareaData();
        table = (DefaultTableModel) tableListaDeTareas.getModel();
        for (Tarea tar : td.listarTareas()) {
            String estado = null;
            switch(tar.getEstado()){
                case 0: estado = "Pendiente";break;
                case 1: estado = "En Progreso";break;
                case 2: estado = "Inactiva";break;
                case 3: estado = "Completada";break;
            }
            table.addRow(new Object[]{tar.getIdTarea(), tar.getMiembroEq().getIdMiembroEq(), tar.getNombre(), tar.getFechaCreacion(), tar.getFechaCierre(),estado});
        }
    }

    private void initComboEquipos() {
        MiembrosEquipoData med = new MiembrosEquipoData();
        for (MiembrosEquipo me : med.listarTodosMiembrosEquipos()) {
            jcboxPorEquipos.addItem(me);
        }
    }

    private void initComboProyectos() {
        ProyectoData pd = new ProyectoData();
        for (Proyecto proyect : pd.listarProyectos()) {
            jcboxPorProyectos.addItem(proyect);
        }
    }
}
